tidypacks <- tibble(
    package =
        c("broom",
          "dplyr",
          "feather",
          "forcats",
          "ggplot2",
          "haven",
          "httr",
          "hms",
          "jsonlite",
          "lubridate",
          "magrittr",
          "modelr",
          "purrr",
          "readr",
          "readxl",
          "stringr",
          "tibble",
          "rvest",
          "tidyr",
          "xml2"))
